2025-02-11T14:33:15 {"cpu": 0.1484375, "cpu_total": 8, "cpu_usage": 0.0185546875, "memory": 2193.0, "memory_total": 9844.0, "memory_usage": 0.2227752945956928, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "Pipeline covid_poc_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1739284395.467676, "uuid": "b948cb10f53d44fdb9f3f69a96c752f8"}
2025-02-11T14:33:15 {"block_run_id": 1, "block_uuid": "covid_batch_load", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 1: pipeline covid_poc_pipeline block covid_batch_load", "timestamp": 1739284395.704552, "uuid": "6fc67a0f0b7843b498e4d7ddf82c7c75"}
2025-02-11T14:33:15 {"cpu": 0.1484375, "cpu_total": 8, "cpu_usage": 0.0185546875, "memory": 2233.0, "memory_total": 9844.0, "memory_usage": 0.2268386834620073, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "Pipeline covid_poc_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1739284395.830992, "uuid": "3bbb7f46a8984d4e8927acf522c4db39"}
2025-02-11T14:33:16 {"block_run_id": 4, "block_uuid": "dim_date", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 4: pipeline covid_poc_pipeline block dim_date", "timestamp": 1739284396.753484, "uuid": "50106e319c4f4238874491c78eda289f"}
2025-02-11T14:33:16 {"block_run_id": 3, "block_uuid": "dim_country", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 3: pipeline covid_poc_pipeline block dim_country", "timestamp": 1739284396.75348, "uuid": "6dc8455c63654b18b475cef7772068c8"}
2025-02-11T14:33:16 {"block_run_id": 7, "block_uuid": "fact_top_frequency", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 7: pipeline covid_poc_pipeline block fact_top_frequency", "timestamp": 1739284396.781911, "uuid": "f35856d409814b16ace84d80193c537c"}
2025-02-11T14:33:16 {"block_run_id": 6, "block_uuid": "fact_covid_daily", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 6: pipeline covid_poc_pipeline block fact_covid_daily", "timestamp": 1739284396.798042, "uuid": "85fe1cc9e47847e4926016353a267ba5"}
2025-02-11T14:33:21 {"block_run_id": 1, "block_uuid": "covid_batch_load", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "BlockRun 1 (block_uuid: covid_batch_load) completes.", "timestamp": 1739284401.849971, "uuid": "6f8c6b58c1a64ee6a1cb2bd4809fddd5"}
2025-02-11T14:33:26 {"cpu": 0.16845703125, "cpu_total": 8, "cpu_usage": 0.02105712890625, "memory": 2636.0, "memory_total": 9844.0, "memory_usage": 0.26777732629012596, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "Pipeline covid_poc_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1739284406.027607, "uuid": "a357ba9e68214ce7802deeab31bde73e"}
2025-02-11T14:33:26 {"block_run_id": 6, "block_uuid": "fact_covid_daily", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "BlockRun 6 (block_uuid: fact_covid_daily) completes.", "timestamp": 1739284406.115993, "uuid": "08c2b9c546e04529b86136205bd0db13"}
2025-02-11T14:33:26 {"block_run_id": 3, "block_uuid": "dim_country", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "BlockRun 3 (block_uuid: dim_country) completes.", "timestamp": 1739284406.153608, "uuid": "4eb9b88e7dc042a8a7e89b3a08329327"}
2025-02-11T14:33:26 {"block_run_id": 7, "block_uuid": "fact_top_frequency", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "BlockRun 7 (block_uuid: fact_top_frequency) completes.", "timestamp": 1739284406.153688, "uuid": "b21bd840de8e4f7ca1f359374036aadf"}
2025-02-11T14:33:26 {"block_run_id": 4, "block_uuid": "dim_date", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "BlockRun 4 (block_uuid: dim_date) completes.", "timestamp": 1739284406.169947, "uuid": "ea2cad4e02f548c886e1f3caa96a88be"}
2025-02-11T14:33:26 {"block_run_id": 5, "block_uuid": "dim_province_state", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 5: pipeline covid_poc_pipeline block dim_province_state", "timestamp": 1739284406.786346, "uuid": "597444306b3442cea4d3a65c99304ec6"}
2025-02-11T14:33:26 {"block_run_id": 5, "block_uuid": "dim_province_state", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "EXCEPTION", "message": "BlockRun 5 (block_uuid: dim_province_state) failed.", "timestamp": 1739284406.86799, "uuid": "342b1fc668ea429a88948a61c91ce87f", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2061, in _execute_block\n    block_function = self._validate_execution(decorated_functions, input_vars)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1781, in _validate_execution\n    raise Exception(\nException: Block dim_province_state may have too many upstream dependencies. It expected to have 0 arguments, but received 1. Confirm that the @data_loader method declaration has the correct number of arguments.\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1161, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1697, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1443, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 788, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1702, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 197, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "Block dim_province_state may have too many upstream dependencies. It expected to have 0 arguments, but received 1. Confirm that the @data_loader method declaration has the correct number of arguments."}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1691, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1570, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1910, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2061, in _execute_block
    block_function = self._validate_execution(decorated_functions, input_vars)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1781, in _validate_execution
    raise Exception(
Exception: Block dim_province_state may have too many upstream dependencies. It expected to have 0 arguments, but received 1. Confirm that the @data_loader method declaration has the correct number of arguments.
2025-02-11T14:33:35 {"cpu": 0.16650390625, "cpu_total": 8, "cpu_usage": 0.02081298828125, "memory": 2208.0, "memory_total": 9844.0, "memory_usage": 0.22429906542056074, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "covid_poc_pipeline", "hostname": "b443fad0382b", "level": "INFO", "message": "Pipeline covid_poc_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1739284415.311869, "uuid": "501dcfced97e4e199bb6b5d72024f935"}
